In [1]:
!pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [17]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [3]:
1e-4

0.0001

In [6]:
np.random.randn(3) +1e-4

array([ 0.08822062,  0.89321005, -0.20149239])

In [133]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) +1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0,1,0)
    
        
    def fit(self, X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias :\n {X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch +1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"Predicted value after forward pass: \n {y_hat}")
            
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
            print(f"updated weights after epoch:{epoch+1}/{self.epochs}:\n {self.weights}")
            print(f"##"*10)
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        print("Z", z)
        return self.activation_function(z)
    
            
        

In [134]:
OR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [142]:
AND = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}

df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [143]:
def prepare_data(df, target_col = "y"):
    X = df.drop(target_col, axis = 1)
    y = df[target_col]
    return X,y

In [144]:
X, y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)

In [145]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [146]:
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [147]:
model_or.fit(X,y)

X with bias :
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
Predicted value after forward pass: 
 [1 0 1 1]
error: 
0   -1
1    0
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:1/10:
 [ 1.44675057 -0.31865023  0.07461059]
####################
--------------------
for epoch >> 2
--------------------
Predicted value after forward pass: 
 [0 0 1 1]
error: 
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:2/10:
 [ 1.34675057 -0.31865023  0.17461059]
####################
--------------------
for epoch >> 3
--------------------
Predicted value after forward pass: 
 [0 0 1 1]
error: 
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:3/10:
 [ 1.24675057 -0.31865023  0.27461059]
####################
--------------------
for epoch >> 4
--------------------
Predicted value after forward pass: 
 [0 0 1 1]
error: 
0    0
1    0
2   -1
3    0
Name: y, dty

In [148]:
model_or.predict(X=[[1,0]])

Z [-0.02786002]


array([0])

In [9]:
obj = Perceptron(eta=0.01, epochs=10)

In [11]:
obj.weights

array([-1.55554119, -1.28481479, -1.49885082])

In [15]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [13]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
obj.fit(X, y)

X with bias :
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
