In [1]:
!pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [2]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [3]:
1e-4

0.0001

In [6]:
np.random.randn(3) +1e-4

array([ 0.08822062,  0.89321005, -0.20149239])

In [7]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) +1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def fit(self, X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias :\n {X_with_bias}")
        

In [9]:
obj = Perceptron(eta=0.01, epochs=10)

In [11]:
obj.weights

array([-1.55554119, -1.28481479, -1.49885082])

In [15]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [13]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
obj.fit(X, y)

X with bias :
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
